### PR TITLE
Mdkessler fix tip 1

### PR DESCRIPTION
**Pull request by mdkessler**
Suggested edits for additional context and readability for those without computational background

**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

**Any more details?**

### CODE REVIEW

**Comment by Benjamin-Lee** [comment]
@mdkessler is this content the same as in #253? If so, I'll close that one and we can focus on this one here.

**Comment by mdkessler** [comment]
@Benjamin-Lee No it is different. This one updated the first tip (ml-concepts). #253 has edits to the into. I'm making another PR now that can replace #253 though - it will be the same content, but broken per sentence as we discussed. I'll also add clearer comments to each PR moving forward.

**Comment by Benjamin-Lee** [comment]
@mdkessler as a note, we're working on a complete rewrite of the first tip, changing its focus to when to use DL in the first place. The current content in it is probably going to be moved elsewhere so the improvements in this patch will likely be moved to different files

**Comment by mdkessler** [comment]
@Benjamin-Lee Sounds good. Thanks for the heads up.

**Comment by Benjamin-Lee** [comment]
@mdkessler I'm going to close this since the majority of the content you fixed ended up being deleted or thoroughly modified. The area that remains is now in the overfitting tip, so we can move that there when you reach it. Thanks again for the help!

**Pull request closed without merging**
