### PR TITLE
Add zipcode metadata required for submission

### PR DESCRIPTION
**Pull request by rasbt**
**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

Adds zip code to author data

### CODE REVIEW

**Review by Benjamin-Lee — APPROVED** [review]

**Comment by Benjamin-Lee** [comment]
Actually, does it make sense to have the value be a list of the number itself? And speaking of which, should we represent it as a string? I do know horrible things can happen when you treat zip codes as numbers, though I doubt it will matter here.

**Comment by rasbt** [comment]
> Actually, does it make sense to have the value be a list of the number itself?

I was thinking that if affiliations is a list, then the zip code should probably also be a list. Although we really don't need multiple zip codes for the submission.

>  I do know horrible things can happen when you treat zip codes as numbers, though I doubt it will matter here.

Yeah, I don't think it matters here. I was thinking of it as just something you would copy and paste into the submission form.

**Comment by cgreene** [comment]
What about just asking that folks include zipcodes for at least one affiliation on that line? I'm wondering if that's easier or harder.

**Comment by fmaguire** [comment]
Also worth noting that not all currently listed authors are based in the US (including myself), therefore don't have zipcodes.

**Comment by rasbt** [comment]
Either way would be fine to me. I think @Benjamin-Lee would just copy & paste the first value into the submission field anyway. I can change it to a single value.

**Comment by Benjamin-Lee** [comment]
Single value works for me. Let’s just go with that since it reduces the complexity.

**Comment by rasbt** [comment]
Good point by @fmaguire 

> Also worth noting that not all currently listed authors are based in the US (including myself), therefore don't have zipcodes.

for those cased, people could add a "- postalcode: ... " entry? Looking at your submission form, Ben, I think either zip code or postal code would be ok.
106531764-dda2df00-64bc-11eb-8a81-0550449bc3e0

**Comment by Benjamin-Lee** [comment]
Let’s go with “postcode” then. An arbitrary string I can put in the form to make them happy will suffice.

**Comment by rasbt** [comment]
> Let’s go with “postcode” then. An arbitrary string I can put in the form to make them happy will suffice.

alright, done. And like you said, i think we can be flexible because it's just something you have to copy and paste and doesn't go through computational pipelines

**Review by agitter — APPROVED** [review]

**Pull request merged**
