### PR TITLE
Minor text edit and tried to fix citation tags

### PR DESCRIPTION
**Pull request by ajlee21**
**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [ ] Yes, I added myself or am already a contributor

**Any more details?**

Reading through the manuscript it looks great! Found 2 citations that weren't recognized and so tried to fix these (though I'm not sure if the fixes worked because I wasn't sure how to see the updated compiled manuscript). I also made one minor text edit.

### CODE REVIEW

**Comment by Benjamin-Lee** [comment]
I seem to recall the Hornik DOI not working due to it having parentheses. If the build passes, it should be GTG

**Comment by ajlee21** [comment]
> I seem to recall the Hornik DOI not working due to it having parentheses. If the build passes, it should be GTG

I see. I guess if that's the case I'm not sure what the issue with that tag is.

**Review by Benjamin-Lee — APPROVED** [review]
Looking at the rendered PDF, its GTG

**Review by rasbt — APPROVED** [review]
LGTM

**Pull request merged**
