### PR TITLE
Add updated contributions

### PR DESCRIPTION
**Pull request by Benjamin-Lee**
This is a (almost certainly incomplete) update to ensure that the table of contributions reflects reality.

If I have overlooked your contributions, [don't panic](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Don't_Panic)! Just let me know what I got wrong and I'll be sure to fix it.

### CODE REVIEW

**Comment by agitter** [comment]
@Benjamin-Lee what criteria are you using for the `Substantial contributions` and `Drafting` columns? Some contributors wrote a full first draft of a tip, which should clearly count as `Drafting`, but I'm not sure what else you want to consider.

**Comment by Benjamin-Lee** [comment]
I tried to use my best judgement as I see the ICMJE criteria. Per the ICMJE drafting criterion, it's drafting or `revising it critically for important intellectual content`, so I tried to include those who helped implement the writing by adding comments to PRs, writing PR reviews, _etc._ which I believe should count as critical revision. 

For the substantial contributions column, I tried to include contributors who made serious contributions to the `the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work` such as by condensing the scattered tip proposals down.

How did the deep review differentiate between the two criteria? These papers are somewhat unique due to the authorship method and the ICMJE criteria don't do a great job of capturing it: the contributions/drafting split would normally be for differentiating between researching/writing.

**Comment by agitter** [comment]
Thanks for elaborating.  I'm not questioning your judgement, but I think it is important to have these criteria written down.

> How did the deep review differentiate between the two criteria?

Deep review required authors to have GitHub-visible contributions.  That included contributing and editing text to the manuscript as well as substantial contributions to the design through reviews and issue discussion.  However, I don't recall anyone who made substantial contributions to the design who didn't also write text.

Tracking the ICMJE criteria as the manubot manuscript is drafted is unprecedented as far as I know, so you and the other contributors should proceed with whatever seems fair.

**Comment by rasbt** [comment]
Tracking this sounds a bit challenging, indeed, and I think for such a big (massively collaborative) project, it seems to be crucial that maybe one person who has the complete picture takes the initiative (such as @Benjamin-Lee has done). I am not sure if such tools/plugins exist for github, but the ideal way would maybe be to compile a list/log file of all contributions of all authors as a record or for short review. It seems though that a large chunk of work has been done via the "review" functionality on GitHub (i.e., contributors suggested paragraphs that were then added collaboratively by others such that GitHub-committing the paragraph does not imply that it was written by the commiting person (and some authors may get then forgotten/left out). So, going by GitHub contributions would not be a good way to assess contributions; hence, I don't think this can be in any way automated with the tools we are using and we need to rely on best judgement. 

In any case, it's good to write that down, though :)

**Comment by agitter** [comment]
> it seems to be crucial that maybe one person who has the complete picture takes the initiative

I completely agree with this.  Until we have (or find) the right tools to track all the discussion, reviewing, etc. in addition to git commits, the project lead is best suited to assess contributions.  By making this table public, contributors who have been accidentally left out can easily correct the omission and point to their contributions.

We've had some discussion about archiving and tracking GitHub issue and pull request discussions for Manubot (https://github.com/greenelab/manubot-rootstock/issues/45#issuecomment-454900054) but haven't settled on any specific tools.

**Pull request merged**
