### PR TITLE
[WIP] Merge rootstock

### PR DESCRIPTION
**Pull request by michaelmhoffman**
Merge newest `master` from @manubot/rootstock.

### CODE REVIEW

**Comment by agitter** [comment]
See https://github.com/greenelab/meta-review/pull/251 for how @dhimmel resolved conflicts from the deploy-related changes.

**Comment by michaelmhoffman** [comment]
Thanks, I'll probably start this over.

**Comment by agitter** [comment]
@michaelmhoffman want me to do it?  I updated a different manuscript yesterday so the process is fresh.

**Comment by michaelmhoffman** [comment]
@agitter Yes that would be awesome. Everything I've done here is discardable.

If you could include a transcript of the commands you use to do it in the pull request description that would be invaluable. (I know that's already there from the link you provided, this is just in case it's different.)

**Comment by agitter** [comment]
Replaced by #196 

@michaelmhoffman this rootstock update was worse than usual.  There were conflicts in files that can typically be merged automatically but needed manual correction this time due to past edits I made in this repo.

**Pull request closed without merging**
