### PR TITLE
Address minor errors from #125 and #170

### PR DESCRIPTION
**Pull request by agitter**
**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

**Any more details?**
(see below)

### CODE REVIEW

**Comment by agitter** [comment]
Previous builds had the error `ERROR: No anchor #blackbox for internal URI reference` (e.g. https://travis-ci.org/Benjamin-Lee/deep-rules/builds/509764376#L2191).  Adding a newline after the sub-section header seemed to fix this.  @dhimmel is that the expected behavior?

I also switched the CI badge, which was updated in #170 to the new rootstock CI but not the CI for this repository.

Interestingly, it looks like draft pull requests on GitHub don't trigger CI builds on travis-ci.org.  It works with the new travis-ci.com GitHub app.

**Comment by agitter** [comment]
@dhimmel I'm also wondering whether we should revert the `ci/deploy.sh` changes from `travis-ci.org` to `travis-ci.com`.

**Comment by dhimmel** [comment]
Ah yes these two lines are wrong:

https://github.com/Benjamin-Lee/deep-rules/blob/1b4308438c8675e2480a6cb3dda51d85799806a1/ci/deploy.sh#L52-L53

They should be `.org`... my bad... have made this mistake in many places.

**Comment by dhimmel** [comment]
> Interestingly, it looks like draft pull requests on GitHub don't trigger CI builds on travis-ci.org. It works with the new travis-ci.com GitHub app.

Drafts do trigger CI on travis-ci.com? IIRC draft PRs haven't triggered any travis builds for me. A real annoying bug. I didn't see an issue [here](https://github.com/travis-ci/travis-ci/issues), but we probably should open one.

**Comment by dhimmel** [comment]
> Adding a newline after the sub-section header seemed to fix this. @dhimmel is that the expected behavior?

All the pandoc examples of header identifiers [in the docs](https://pandoc.org/MANUAL.html#header-identifiers) aren't directly followed by text. It doesn't seem to mention a newline is necessary, but perhaps this is intended. It could also be a pandoc bug.

**Comment by agitter** [comment]
> They should be .org... my bad... have made this mistake in many places.

No problem, updated in fae4239

> Drafts do trigger CI on travis-ci.com?

They triggered on this WIP draft pull request https://github.com/gitter-lab/SCINGE/pull/13  I'm not sure what we did differently there to get it to work.

**Pull request merged**
