### PR TITLE
Add Michael Hoffman and ORCIDs to acknowledgements

### PR DESCRIPTION
**Pull request by agitter**
**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

**Any more details?**
Per Michael's suggestion, this pull request will also add ORCIDs to the acknowledgements.  @michaelmhoffman does this formatting look okay to you?

### CODE REVIEW

**Review by rasbt — APPROVED** [review]

**Comment by rasbt** [comment]
This looks good to me. Do you know if the other persons mentioned also have ORCID IDs?

**Comment by agitter** [comment]
> Do you know if the other persons mentioned also have ORCID IDs?

Some, maybe all, of them do.  I can search for and add more ORCIDs if we like the link syntax in Michael's example.

**Comment by rasbt** [comment]
Sounds good, the format looks fine to me

**Comment by michaelmhoffman** [comment]
Can you please use my middle initial. Suggested: `Michael M.\ Hoffman`.

I use ORCIDs for acknowledgments in my own papers and usually just put the linked ORCID number without "ORCID" in parentheses. For example:

```
We would also like to thank Fabio Madeira, Victor Greiff, Shyam Saladi, Anshul Kundaje, Brett Beaulieu-Jones, Paul Brodersen, and Michael M.\ Hoffman ([0000-0002-4517-1562](https://orcid.org/0000-0002-4517-1562)) for their contributions to the discussions that comprised the initial stage of the drafting process.
```

If you have many of them, the repeated "ORCID" will be a lot.

**Review by Benjamin-Lee — APPROVED** [review]

**Comment by agitter** [comment]
I found and added ORCIDs for everyone.  @Benjamin-Lee could you please double-check the links before merging?

**Pull request merged**
